export const REELS_COUNT = 5;
export const ROWS_COUNT = 3;

export enum SlotSymbol {
  SEVEN     = 'SEVEN',
  DIAMOND   = 'DIAMOND',
  BELL      = 'BELL',
  HORSESHOE = 'HORSESHOE',
  HEART     = 'HEART',
  SPADE     = 'SPADE',
  CLUB      = 'CLUB',
  LEMON     = 'LEMON',
  CHERRY    = 'CHERRY',
  WILD      = 'WILD',
  SCATTER   = 'SCATTER',
}

export const REEL_STRIP: SlotSymbol[] = [
  SlotSymbol.CHERRY,    // x8
  SlotSymbol.CHERRY,
  SlotSymbol.CHERRY,
  SlotSymbol.CHERRY,
  SlotSymbol.CHERRY,
  SlotSymbol.CHERRY,
  SlotSymbol.CHERRY,
  SlotSymbol.CHERRY,
  SlotSymbol.LEMON,     
  SlotSymbol.LEMON,
  SlotSymbol.LEMON,
  SlotSymbol.LEMON,
  SlotSymbol.LEMON,
  SlotSymbol.LEMON,
  SlotSymbol.LEMON,
  SlotSymbol.CLUB,      
  SlotSymbol.CLUB,
  SlotSymbol.CLUB,
  SlotSymbol.CLUB,
  SlotSymbol.CLUB,
  SlotSymbol.CLUB,
  SlotSymbol.SPADE,     
  SlotSymbol.SPADE,
  SlotSymbol.SPADE,
  SlotSymbol.SPADE,
  SlotSymbol.SPADE,
  SlotSymbol.SPADE,
  SlotSymbol.HEART,     
  SlotSymbol.HEART,
  SlotSymbol.HEART,
  SlotSymbol.HEART,
  SlotSymbol.HEART,
  SlotSymbol.HORSESHOE, 
  SlotSymbol.HORSESHOE,
  SlotSymbol.HORSESHOE,
  SlotSymbol.HORSESHOE,
  SlotSymbol.BELL,      
  SlotSymbol.BELL,
  SlotSymbol.BELL,
  SlotSymbol.DIAMOND,   
  SlotSymbol.DIAMOND,
  SlotSymbol.SEVEN,     
  SlotSymbol.WILD,      
  SlotSymbol.WILD,
  SlotSymbol.SCATTER,   
  SlotSymbol.SCATTER,
];


export const PAYTABLE: Record<SlotSymbol, [number, number, number]> = {
  [SlotSymbol.SEVEN]:     [100, 250, 500],
  [SlotSymbol.DIAMOND]:   [50,  100, 200],
  [SlotSymbol.BELL]:      [20,  50,  100],
  [SlotSymbol.HORSESHOE]: [10,  25,  50],
  [SlotSymbol.HEART]:     [5,   15,  30],
  [SlotSymbol.SPADE]:     [5,   15,  30],
  [SlotSymbol.CLUB]:      [3,   10,  20],
  [SlotSymbol.LEMON]:     [2,   5,   10],
  [SlotSymbol.CHERRY]:    [1,   3,   5],
  [SlotSymbol.WILD]:      [0,   0,   0],  
  [SlotSymbol.SCATTER]:   [0,   0,   0],  
};


export const SCATTER_PAYTABLE: Record<number, number> = {
  3: 5,  
  4: 20,
  5: 100,
};

export const PAYLINES: number[][] = [
  [1, 1, 1, 1, 1], 
  [0, 0, 0, 0, 0], 
  [2, 2, 2, 2, 2], 
  [0, 1, 2, 1, 0], 
  [2, 1, 0, 1, 2], 
  [0, 0, 1, 2, 2], 
  [2, 2, 1, 0, 0], 
  [1, 0, 0, 0, 1], 
  [1, 2, 2, 2, 1], 
  [0, 1, 0, 1, 0], 
  [2, 1, 2, 1, 2], 
  [1, 0, 1, 0, 1], 
  [1, 2, 1, 2, 1], 
  [0, 0, 2, 0, 0], 
  [2, 2, 0, 2, 2], 
  [0, 2, 0, 2, 0], 
  [2, 0, 2, 0, 2], 
  [0, 1, 1, 1, 0], 
  [2, 1, 1, 1, 2], 
  [1, 1, 0, 1, 1],
];